version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "Europe/London"
    reviewers:
      - tanyapowell
    open-pull-requests-limit: 10
